### ISSUE TITLE
请问你的暗影精灵3如何插上BCM94360CS2？

### ISSUE THREAD

**Issue by captainz236** [shimakazechan/OMEN-by-HP-3-Hackintosh#1]
![IMAGE 2020-02-27 20:18:39](https://user-images.githubusercontent.com/58735384/75444414-57be1000-599e-11ea-8f3b-5c7e1eed5d5e.jpg)
![IMAGE 2020-02-27 20:18:47](https://user-images.githubusercontent.com/58735384/75444424-5c82c400-599e-11ea-8fe9-49968da68b8e.jpg)
我把BCM94360CS2插上去发觉会顶到电池，请问你如何解决的？

**Comment by shimakazechan** [comment]
放棄固定把 pcd斷後面的
